import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import localFont from "next/font/local"
import "@/app/globals.css";

const interTight = Inter_Tight({
  variable: "--font-inter-tight",
  subsets: ["latin"],
});


const satoshi = localFont({
  src: "./fonts/Satoshi-Black.otf", 
  variable: "--font-satoshi",
});
export const metadata: Metadata = {
  title: "Hatem",
  description: "Generated by Hatem",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interTight.className} ${interTight.variable} ${satoshi.variable} antialiased`}>{children}</body>
    </html>
  );
}
