import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import "@/app/globals.css";

const interTight = Inter_Tight({
  variable: "--font-inter-tight", 
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Hatem",
  description: "Generated by Hatem",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interTight.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
